version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:latest
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    
    container_name: oracle-db
    ports:
      - "15210:1521"
    environment:
      - ORACLE_SID=${ORACLE_SID}
      - ORACLE_PDB=${ORACLE_PDB}
      - ORACLE_PWD=${ORACLE_PWD}
      - ORACLE_USER=${DATABASE_USERNAME}
      - ORACLE_USER_PWD=${DATABASE_PASSWORD}
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./init.sql:/opt/oracle/scripts/setup/init.sql
      - ./setup.sh:/opt/oracle/scripts/setup/setup.sh
    restart: always
  
  backend-orii:
    build: .
    depends_on:
      - oracle-db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - spring.mail.username=${MAIL_USERNAME}
      - spring.mail.password=${MAIL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8080:8080"
    container_name: backend-orii

     
volumes:
  oracle-data: